# Streamlined CI/CD Pipeline for Azure Static Web Apps
# Production-like workflow with simplified complexity

name: Deploy Resume Website

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["main"]

jobs:
  # PR validation and staging deployment
  pull_request_workflow:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: PR Validation & Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate content
        run: |
          echo "🔍 Validating website content..."
          
          # Check required files exist
          if [ ! -f "src/index.html" ]; then
            echo "❌ src/index.html not found"
            exit 1
          fi
          
          # Basic HTML validation
          if ! grep -q "<title>" src/index.html; then
            echo "❌ Missing title tag"
            exit 1
          fi
          
          if ! grep -q "Jyothi Prakash" src/index.html; then
            echo "❌ Missing expected content"
            exit 1
          fi
          
          echo "✅ Content validation passed"

      - name: Deploy to staging
        id: staging_deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/src"
          output_location: ""

      - name: Comment PR with staging info
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Staging deployed successfully!**\n\n✅ Content validation passed\n✅ Staging environment ready for review\n\nPlease review and approve when ready.`
            });

  # Production deployment (only when PR is merged to main)
  production_deployment:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Production Deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/src"
          output_location: ""

      - name: Production deployment success
        run: |
          echo "🎉 Production deployment completed!"
          echo "🌐 Live at: https://mango-water-0502ea200.1.azurestaticapps.net"

  # Cleanup staging when PR is closed
  cleanup_staging:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Cleanup Staging
    steps:
      - name: Remove staging environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
